### ISSUE TITLE
Plugin mechanism with a poetry managed package

### ISSUE THREAD

**Issue by jack-mcivor** [scientific-python/repo-review#195]
Is it possible to write custom checks whilst using a poetry style pyproject.toml setup?

My attempt is:
```toml
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "ex-repo-review"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.10"
repo-review = {extras = ["cli"], version = "^0.10.4"}

[project.entry-points."repo_review.checks"]
examples = "ex_repo_review.checks:repo_review_checks"
```
But this does not seem to register the plugin
```
 ╭─ Error ─────────────────────────────────────────────────────╮
 │ No checks registered. Please install a repo-review plugin.  │
 ╰─────────────────────────────────────────────────────────────╯
```

I guess the [poetry way of describing entry points](https://python-poetry.org/docs/pyproject/#scripts) might be required, but I cannot get this to work also
```toml
[tool.poetry.scripts."repo_review.checks"]
examples = "ex_repo_review.checks:repo_review_checks"
```
Causes an error on `poetry install`
```
# The Poetry configuration is invalid:
#   - data.scripts.repo_review.checks must be valid exactly by one definition (0 matches found)
```

My project structure is
```
├── README.md
├── poetry.lock
├── pyproject.toml
└── src
    └── ex_repo_review
        ├── __init__.py
        └── checks.py
```
And this seems to work fine without poetry & a standard `[project]` table.

I suspect maybe I'm doing something incorrect with the quoting but can't wrap my head around it
